// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MainCSS() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n        /* General Reset */\n        * {\n            margin: 0;\n            padding: 0;\n            box-sizing: border-box;\n        }\n\n        body {\n            font-family: Arial, sans-serif;\n            display: flex;\n            height: 100vh;\n            background-color: #121212;\n            /* Dark background */\n            color: #e0e0e0;\n            /* Light text color */\n        }\n\n        .sidebar {\n            width: 250px;\n            background-color: #1e1e1e;\n            /* Slightly lighter than main background */\n            padding: 20px;\n            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.5);\n        }\n\n        .sidebar h1 {\n            font-size: 1.5rem;\n            color: #90caf9;\n            /* Soft blue */\n            margin-bottom: 20px;\n        }\n\n        .sidebar ul {\n            list-style: none;\n        }\n\n        .sidebar li {\n            padding: 10px;\n            margin: 10px 0;\n            background-color: #2a2a2a;\n            /* Dark gray for menu items */\n            border-radius: 4px;\n            cursor: pointer;\n            transition: background-color 0.3s, color 0.3s;\n        }\n\n        .sidebar li:hover {\n            background-color: #90caf9;\n            /* Highlight on hover */\n            color: #121212;\n            /* Dark text for contrast */\n        }\n        .sidebar li:hover > a {\n            color: #121212;\n        }\n\n        .main-content {\n            flex: 1;\n            padding: 20px;\n        }\n        \n        a, a:visited {\n            color: #e0e0e0;\n        }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
